timezone: Europe/Rome
baseurl: /eu
permalink: pretty
remote_theme: giovian/ui@main
favicon:
  ico: /assets/images/favicon.ico

nav: true
footer: true

# DEFAULTS
defaults:
  - scope:
      path: assets/help.md
    values:
      sidebar: []