name: Fetch XML feed
on:
  schedule:
    # Run at 00:01 06:01 12:01 18:01 UTC every day
    - cron: '1 0/6 * * *'

jobs:
  fetch:
    name: Fetch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: wget "https://www.movimento5stelle.eu/feed/" --output-document=assets/m5sfeed.xml
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4
